package org.adancau.doneapi.auth;

final class RecoveryMailCopy {
  private RecoveryMailCopy() {}
  static String[] forLanguage(String language) {
    return switch(language) {
      default -> new String[]{"Reset your DONE password","Use the link below to choose a new password. The link expires in {minutes} minutes and can be used once.","Your DONE password was changed","Your password was changed and all existing sessions were signed out. If this was not you, reset your password immediately or contact support.","If you did not request this, you can ignore this email."};
      case "ro" -> new String[]{"Resetează parola DONE","Folosește linkul de mai jos pentru a alege o parolă nouă. Linkul expiră în {minutes} minute și poate fi folosit o singură dată.","Parola ta DONE a fost schimbată","Parola a fost schimbată și toate sesiunile existente au fost închise. Dacă nu ai făcut tu asta, resetează imediat parola sau contactează suportul.","Dacă nu ai cerut resetarea, poți ignora acest email."};
      case "es" -> new String[]{"Restablece tu contraseña de DONE","Usa el enlace para elegir una nueva contraseña. Caduca en {minutes} minutos y solo puede usarse una vez.","Tu contraseña de DONE ha cambiado","Tu contraseña ha cambiado y todas las sesiones se han cerrado. Si no has sido tú, restablece la contraseña de inmediato o contacta con soporte.","Si no lo has solicitado, puedes ignorar este correo."};
      case "it" -> new String[]{"Reimposta la password di DONE","Usa il link per scegliere una nuova password. Scade tra {minutes} minuti e può essere usato una sola volta.","La tua password di DONE è stata modificata","La password è stata modificata e tutte le sessioni sono state chiuse. Se non sei stato tu, reimposta subito la password o contatta il supporto.","Se non hai richiesto la reimpostazione, ignora questa email."};
      case "fr" -> new String[]{"Réinitialisez votre mot de passe DONE","Utilisez le lien pour choisir un nouveau mot de passe. Il expire dans {minutes} minutes et ne peut être utilisé qu’une fois.","Votre mot de passe DONE a été modifié","Votre mot de passe a été modifié et toutes les sessions ont été fermées. Si ce n’était pas vous, réinitialisez immédiatement le mot de passe ou contactez l’assistance.","Si vous n’avez pas fait cette demande, ignorez cet email."};
      case "de" -> new String[]{"Setze dein DONE-Passwort zurück","Wähle über den Link ein neues Passwort. Der Link läuft nach {minutes} Minuten ab und kann nur einmal verwendet werden.","Dein DONE-Passwort wurde geändert","Dein Passwort wurde geändert und alle Sitzungen wurden abgemeldet. Falls du das nicht warst, setze dein Passwort sofort zurück oder kontaktiere den Support.","Wenn du dies nicht angefordert hast, ignoriere diese E-Mail."};
      case "pl" -> new String[]{"Zresetuj hasło DONE","Użyj linku, aby wybrać nowe hasło. Link wygasa za {minutes} minut i można go użyć tylko raz.","Twoje hasło DONE zostało zmienione","Hasło zostało zmienione i wszystkie sesje zostały wylogowane. Jeśli to nie Ty, natychmiast zresetuj hasło lub skontaktuj się z pomocą.","Jeśli nie wysłano tej prośby, zignoruj ten email."};
      case "hi" -> new String[]{"अपना DONE पासवर्ड रीसेट करें","नया पासवर्ड चुनने के लिए नीचे दिए लिंक का उपयोग करें। लिंक {minutes} मिनट में समाप्त हो जाएगा और केवल एक बार इस्तेमाल किया जा सकता है।","आपका DONE पासवर्ड बदल दिया गया है","आपका पासवर्ड बदल दिया गया है और सभी सत्रों से साइन आउट कर दिया गया है। यदि आपने ऐसा नहीं किया, तो तुरंत पासवर्ड रीसेट करें या सहायता से संपर्क करें।","यदि आपने यह अनुरोध नहीं किया, तो इस ईमेल को अनदेखा कर सकते हैं।"};
      case "ja" -> new String[]{"DONEのパスワードをリセット","下のリンクから新しいパスワードを設定してください。リンクの有効期限は{minutes}分で、一度だけ使用できます。","DONEのパスワードが変更されました","パスワードが変更され、すべてのセッションからログアウトしました。心当たりがない場合は、すぐにパスワードをリセットするか、サポートに連絡してください。","リセットを依頼していない場合は、このメールを無視してください。"};
    };
  }
}
