#!/usr/bin/env python3
"""Translate the local .env into ignored Spring properties; never print secrets."""
import os, shlex
from pathlib import Path
root=Path(__file__).resolve().parent.parent
values={}
for number,line in enumerate((root/'.env').read_text().splitlines(),1):
    line=line.strip()
    if not line or line.startswith('#'):continue
    if line.startswith('export '):line=line[7:]
    key,separator,value=line.partition('=')
    if not separator or not key.replace('_','').isalnum():raise SystemExit(f'Invalid .env line {number}')
    tokens=shlex.split(value,comments=True)
    if len(tokens)>1:raise SystemExit(f'Quote values containing spaces on .env line {number}')
    values[key]=tokens[0] if tokens else ''
if not values.get('DATABASE_URL','').startswith('jdbc:mysql://'):raise SystemExit('Set DATABASE_URL to jdbc:mysql://localhost:3306/done_db in .env first.')
for key in ('DATABASE_USER','DATABASE_PASSWORD','JWT_SECRET'):
    if not values.get(key):raise SystemExit(f'Set {key} in .env first.')
def escape(value):
    return value.replace('\\','\\\\').replace('\n','\\n').replace('\r','\\r').replace('\t','\\t').replace(' ','\\ ')
# Spring environment variables take precedence over imported file properties.
# This imported document is never active in production.
lines=['# Generated by scripts/configure-local.py. Never commit this file.','spring.config.activate.on-profile=!prod']
for key,value in values.items():
    lines.append(key+'='+escape(value))
path=root/'config'/'local.properties';path.parent.mkdir(exist_ok=True)
fd=os.open(path,os.O_WRONLY|os.O_CREAT|os.O_TRUNC,0o600)
with os.fdopen(fd,'w') as f:f.write('\n'.join(lines)+'\n')
os.chmod(path,0o600)
print('Created config/local.properties (0600). Run DoneApiApplication with the backend project as working directory.')
