ALTER TABLE appliances DROP CONSTRAINT appliances_kind_check;
ALTER TABLE appliances ADD CONSTRAINT appliances_kind_check CHECK(kind IN ('washer','dryer','dishwasher','oven','hob','custom'));
ALTER TABLE appliances ALTER COLUMN name TYPE TEXT;
ALTER TABLE programs ALTER COLUMN name TYPE TEXT;
ALTER TABLE appliance_sessions ALTER COLUMN program_name TYPE TEXT;
ALTER TABLE households ALTER COLUMN name TYPE TEXT;
ALTER TABLE app_users ALTER COLUMN display_name TYPE TEXT;
ALTER TABLE app_users ADD COLUMN onboarded BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE programs ADD COLUMN localization_key VARCHAR(200);
ALTER TABLE programs ADD COLUMN is_custom BOOLEAN NOT NULL DEFAULT TRUE;
UPDATE programs SET localization_key=name,is_custom=FALSE WHERE suggested=TRUE;
DROP INDEX uq_program_name;
CREATE UNIQUE INDEX uq_program_value ON programs(appliance_id,name,minutes,is_custom,COALESCE(localization_key,''));
ALTER TABLE appliance_sessions ADD COLUMN source_program_id UUID;
ALTER TABLE appliance_sessions ADD COLUMN program_localization_key VARCHAR(200);
ALTER TABLE appliance_sessions ADD COLUMN program_custom BOOLEAN NOT NULL DEFAULT TRUE;
UPDATE appliance_sessions s SET source_program_id=s.program_id,program_localization_key=p.localization_key,program_custom=p.is_custom FROM programs p WHERE s.program_id=p.id;
UPDATE appliance_sessions SET program_localization_key='timer.session',program_custom=FALSE WHERE mode='stopwatch' AND program_name='Gătit';
ALTER TABLE appliance_sessions ADD COLUMN measured_program_name TEXT;
ALTER TABLE appliance_sessions ADD COLUMN measured_program_minutes INTEGER;
ALTER TABLE appliance_sessions ADD CONSTRAINT ck_measured_program CHECK((measured_program_name IS NULL AND measured_program_minutes IS NULL) OR (measured_program_name IS NOT NULL AND measured_program_minutes BETWEEN 1 AND 1440 AND mode='stopwatch' AND completed_at IS NOT NULL AND canceled_at IS NULL));
ALTER TABLE activity_events ADD COLUMN title_key VARCHAR(200);
ALTER TABLE activity_events ADD COLUMN message_key VARCHAR(200);
ALTER TABLE activity_events ADD COLUMN message_arguments TEXT;
ALTER TABLE activity_events ADD COLUMN program_snapshot TEXT;
